:lipstick: add slack icon
afsy/website pull request #267
Opened 2021-11-22 16:39 UTC by matyo91

Add slack icon from #266 

Note : il y a la génération des icones qui est faite par rapport à un logiciel que je n'ai pas ici : assets/images/icon-s9ddb067304.png

La PR est faite à la main. Il faudra faire une repasse pour l'intégrer dans le soft de creation d'icones.

2021-11-22 16:55 UTC, Nek- requested changes
Haha merci pour l'ajout @matyo91 \o/

2021-11-22 16:55 UTC, Nek- commented on assets/css/icons.css
> +.icon-slack-white{background:url('../images/icon/slack-white.png') no-repeat;width: 32px;height: 32px}
C'est un fichier minifié il faut mettre ça dans un autre fichier! (même si ça a du sens ici).

2021-11-23 13:19 UTC, matyo91 commented on assets/css/icons.css
> +.icon-slack-white{background:url('../images/icon/slack-white.png') no-repeat;width: 32px;height: 32px}
Disons que le plus simple serait de faire une repasse avec le logiciel qui fait le process de minification. Mais je n'ai pas la référence.

2021-11-23 14:11 UTC, Nek- commented on assets/css/icons.css
> +.icon-slack-white{background:url('../images/icon/slack-white.png') no-repeat;width: 32px;height: 32px}
Je crois surtout que ce fichier est généré (ou au moins "était") et n'aurait jamais dû être commit en fait.

2021-11-23 14:59 UTC, matyo91 commented on assets/css/icons.css
> +.icon-slack-white{background:url('../images/icon/slack-white.png') no-repeat;width: 32px;height: 32px}
J'ai déplacé le code dans un autre fichier CSS. Mais dans un sens, cela aurait été mieux de tout faire par le logiciel qui génère.
Mais effectivement c'est fonctionnel.

2022-01-16 09:17 UTC, merged